### ISSUE TITLE
Create all possible tests for NifCreator class

### ISSUE THREAD

**Issue by igoraresti** [CursoJava-Bilbao/JavaSE-CP8-NIF_DNI#1]
In the test package is the NifCreatorTest class. There we have to create all possible tests to verify that the NifCreator class is working fine.
Check how We did testing in other repositories of this Organization.

**Comment by Merinigo** [comment]
He creado una branch con los test que he hecho yo, pero no se si es asi como se tiene que hacer.

**Comment by igoraresti** [comment]
Hay que refactorizar el código para el caso en el que el dni introducido no sea de 8 cifras y de devuelva null
